version: '3.8'

services:
  freelance-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MONGO_DB_CHAT=${MONGO_DB_CHAT}
        - MONGO_DB=${MONGO_DB}
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    ports:
      - "3000:3000"  # Next.js app
      - "4000:4000"  # Socket.IO server
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - MONGO_DB_CHAT=${MONGO_DB_CHAT}
      - MONGO_DB=${MONGO_DB}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add MongoDB service if needed
  # mongodb:
  #   image: mongo:7
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - mongodb_data:/data/db
  #   restart: unless-stopped

# volumes:
#   mongodb_data:
