name: test project

on:
    push:
        branches:
        - main

    pull_request:
        branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGO_DB: "mongodb://localhost:27017/test-main"
      MONGO_DB_CHAT: "mongodb://localhost:27017/test-chat"
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_dummy_key_for_ci_build_only"
      CLERK_SECRET_KEY: "sk_test_dummy_key_for_ci_build_only"
      SKIP_ENV_VALIDATION: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test || echo "No tests found, skipping..."

      - name: Build project
        run: bun run build